name: AdLucem
favicon: null
layout_spectrum: 0.25392
typography_spectrum: 0.24374
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020100'
    - '#464542'
    - '#9a9e8d'
    - '#cec8ba'
    - '#f6efe7'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
