name: AdLucem
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5331472386606038
  lightness: 0.678140525938943
  saturation: 0.1624240605160594
  rhythmicContrast: 0.7113271711859852
purpose: []
